'use client';

import { useState } from 'react';
import { useAuth } from '@/hooks/useAuth';
import { 
  CreditCard, 
  CheckCircle, 
  Clock, 
  DollarSign, 
  ShieldCheck, 
  Lock, 
  Receipt,
  Search,
  Filter,
  Download,
  RotateCcw,
  Ban,
  CheckCircle2,
  Calendar,
  AlertCircle
} from 'lucide-react';

interface PaymentItem {
  id: number;
  orderId: number;
  customerId: number;
  customerName: string;
  amount: number;
  currency: string;
  method: 'CARD' | 'PAYHERE' | 'STRIPE' | 'CASH_ON_DELIVERY';
  status: 'PAID' | 'PENDING' | 'REFUNDED' | 'FAILED' | 'VOIDED';
  reference: string;
  invoiceNumber: string;
  gatewayMessage: string;
  createdAt: string;
}

const INITIAL_PAYMENTS: PaymentItem[] = [
  {
    id: 1,
    orderId: 1001,
    customerId: 1,
    customerName: 'Kavindu Perera',
    amount: 4200.00,
    currency: 'LKR',
    method: 'CARD',
    status: 'PAID',
    reference: 'TXN-80921-VISA',
    invoiceNumber: 'INV-2026-00101',
    gatewayMessage: 'Payment processed successfully via Visa gateway',
    createdAt: 'Today, 14:20'
  },
  {
    id: 2,
    orderId: 1002,
    customerId: 2,
    customerName: 'Nimesha Silva',
    amount: 8900.00,
    currency: 'LKR',
    method: 'PAYHERE',
    status: 'PAID',
    reference: 'TXN-80920-PAYHERE',
    invoiceNumber: 'INV-2026-00102',
    gatewayMessage: 'Approved through PayHere gateway',
    createdAt: 'Today, 13:45'
  },
  {
    id: 3,
    orderId: 1003,
    customerId: 3,
    customerName: 'Dilshan Jayasuriya',
    amount: 2450.00,
    currency: 'LKR',
    method: 'CASH_ON_DELIVERY',
    status: 'PENDING',
    reference: 'TXN-80919-COD',
    invoiceNumber: 'INV-2026-00103',
    gatewayMessage: 'Cash on delivery awaiting dispatch confirmation',
    createdAt: 'Today, 12:10'
  },
  {
    id: 4,
    orderId: 1004,
    customerId: 4,
    customerName: 'Saman Kumara',
    amount: 1850.00,
    currency: 'LKR',
    method: 'STRIPE',
    status: 'REFUNDED',
    reference: 'TXN-80918-STRIPE',
    invoiceNumber: 'INV-2026-00104',
    gatewayMessage: 'Customer requested return and refund processed',
    createdAt: 'Yesterday, 16:30'
  },
  {
    id: 5,
    orderId: 1005,
    customerId: 5,
    customerName: 'Amara Weerasinghe',
    amount: 5600.00,
    currency: 'LKR',
    method: 'CARD',
    status: 'PAID',
    reference: 'TXN-80917-MC',
    invoiceNumber: 'INV-2026-00105',
    gatewayMessage: 'Approved via MasterCard gateway',
    createdAt: 'Yesterday, 11:15'
  }
];

export default function PaymentDashboardPage() {
  const { user, isSuperAdmin, hasRole } = useAuth();
  const [payments, setPayments] = useState<PaymentItem[]>(INITIAL_PAYMENTS);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedStatus, setSelectedStatus] = useState<string>('ALL');
  const [selectedPayment, setSelectedPayment] = useState<PaymentItem | null>(null);

  const isAuthorized = isSuperAdmin || hasRole('PAYMENT_ADMIN');

  if (!isAuthorized) {
    return (
      <div className="glass-card rounded-2xl p-8 max-w-lg mx-auto text-center space-y-4">
        <div className="h-12 w-12 rounded-2xl bg-red-500/10 border border-red-500/20 text-red-400 flex items-center justify-center mx-auto">
          <Lock className="w-6 h-6" />
        </div>
        <h2 className="text-lg font-bold text-white">Access Restricted</h2>
        <p className="text-xs text-ink-muted leading-relaxed">
          You do not have administrative permissions to access Module 2 (Payment Management).
          This panel is exclusively reserved for the Payment Administrator (Anaf M.K.A.S.) or Super Admin.
        </p>
      </div>
    );
  }

  // Action Handlers
  const handleUpdateStatus = (id: number, newStatus: 'PAID' | 'REFUNDED' | 'VOIDED') => {
    setPayments(prev =>
      prev.map(p => {
        if (p.id === id) {
          const msg = newStatus === 'PAID'
            ? 'Manually verified and confirmed by Payment Admin'
            : newStatus === 'REFUNDED'
            ? 'Refund processed to customer source account'
            : 'Transaction marked as voided';
          return { ...p, status: newStatus, gatewayMessage: msg };
        }
        return p;
      })
    );
  };

  const handleDownloadInvoice = (item: PaymentItem) => {
    const content = `SARASAVI PAGES (PVT) LTD - PAYMENT INVOICE
======================================================
Invoice Number: ${item.invoiceNumber}
Transaction Ref: ${item.reference}
Date: ${item.createdAt}
Customer Name: ${item.customerName} (ID: ${item.customerId})
Order Reference: #${item.orderId}
Payment Method: ${item.method}
Payment Status: ${item.status}
------------------------------------------------------
Total Paid: ${item.currency} ${item.amount.toLocaleString(undefined, { minimumFractionDigits: 2 })}
Gateway Log: ${item.gatewayMessage}
======================================================
Generated by Sarasavi Pages Module 2: Payment Administration
`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Invoice-${item.invoiceNumber}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  // KPIs
  const totalRevenue = payments
    .filter(p => p.status === 'PAID')
    .reduce((acc, p) => acc + p.amount, 0);

  const processedCount = payments.filter(p => p.status === 'PAID').length;
  const pendingCount = payments.filter(p => p.status === 'PENDING').length;
  const refundedCount = payments.filter(p => p.status === 'REFUNDED').length;

  const filteredPayments = payments.filter(p => {
    const matchesSearch =
      p.reference.toLowerCase().includes(searchTerm.toLowerCase()) ||
      p.customerName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      p.invoiceNumber.toLowerCase().includes(searchTerm.toLowerCase()) ||
      p.orderId.toString().includes(searchTerm);

    const matchesStatus = selectedStatus === 'ALL' || p.status === selectedStatus;
    return matchesSearch && matchesStatus;
  });

  return (
    <div className="space-y-6 pb-12">
      {/* Top Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 text-xs font-semibold mb-2">
            <CreditCard className="w-3.5 h-3.5" />
            Module 2 — Payment Administration
          </div>
          <h1 className="text-2xl font-bold font-display text-white">Payment & Gateway Operations</h1>
          <p className="text-xs text-ink-muted mt-1">
            Assigned Owner: <span className="text-emerald-400 font-semibold">Anaf M.K.A.S. (IT25102345)</span> • Role: <span className="font-mono text-white">PAYMENT_ADMIN</span>
          </p>
        </div>

        <div className="flex items-center gap-2 px-3 py-1.5 rounded-xl bg-surface-card border border-surface-border text-xs font-mono text-emerald-400">
          <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
          <span>Gateway: Multi-Channel Gateway Active</span>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="glass-card p-5 rounded-2xl">
          <div className="flex items-center justify-between">
            <span className="text-xs font-medium text-ink-muted">Total Paid Revenue</span>
            <div className="h-8 w-8 rounded-lg bg-emerald-500/10 text-emerald-400 flex items-center justify-center">
              <DollarSign className="w-4 h-4" />
            </div>
          </div>
          <div className="mt-3">
            <span className="text-2xl font-bold text-white font-display">
              LKR {totalRevenue.toLocaleString(undefined, { minimumFractionDigits: 2 })}
            </span>
          </div>
          <p className="text-[11px] text-emerald-400 mt-1 flex items-center gap-1 font-mono">
            Active Verified Transactions
          </p>
        </div>

        <div className="glass-card p-5 rounded-2xl">
          <div className="flex items-center justify-between">
            <span className="text-xs font-medium text-ink-muted">Processed Payments</span>
            <div className="h-8 w-8 rounded-lg bg-brand-500/10 text-brand-400 flex items-center justify-center">
              <Receipt className="w-4 h-4" />
            </div>
          </div>
          <div className="mt-3">
            <span className="text-2xl font-bold text-white font-display">
              {processedCount} Orders
            </span>
          </div>
          <p className="text-[11px] text-ink-faint mt-1">Visa, MasterCard, PayHere</p>
        </div>

        <div className="glass-card p-5 rounded-2xl">
          <div className="flex items-center justify-between">
            <span className="text-xs font-medium text-ink-muted">Pending Verifications</span>
            <div className="h-8 w-8 rounded-lg bg-amber-500/10 text-amber-400 flex items-center justify-center">
              <Clock className="w-4 h-4" />
            </div>
          </div>
          <div className="mt-3">
            <span className="text-2xl font-bold text-white font-display">
              {pendingCount} Orders
            </span>
          </div>
          <p className="text-[11px] text-amber-400 mt-1">Cash on Delivery & Bank Slips</p>
        </div>

        <div className="glass-card p-5 rounded-2xl">
          <div className="flex items-center justify-between">
            <span className="text-xs font-medium text-ink-muted">Refunds & Voids</span>
            <div className="h-8 w-8 rounded-lg bg-rose-500/10 text-rose-400 flex items-center justify-center">
              <RotateCcw className="w-4 h-4" />
            </div>
          </div>
          <div className="mt-3">
            <span className="text-2xl font-bold text-white font-display">
              {refundedCount} Cases
            </span>
          </div>
          <p className="text-[11px] text-rose-400 mt-1">Settled / Closed accounts</p>
        </div>
      </div>

      {/* Transactions Directory Table */}
      <div className="glass-card rounded-2xl p-6">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-4">
          <div>
            <h2 className="text-base font-bold text-white">Payment Transactions & Financial Audit Trail</h2>
            <p className="text-xs text-ink-muted mt-0.5">Manage and reconcile transactions (UC-PM-01, UC-PM-02)</p>
          </div>

          <div className="flex flex-wrap items-center gap-2">
            {/* Status Filter Tabs */}
            <div className="flex items-center gap-1 bg-surface border border-surface-border rounded-xl p-1 text-xs">
              {['ALL', 'PAID', 'PENDING', 'REFUNDED'].map(st => (
                <button
                  key={st}
                  onClick={() => setSelectedStatus(st)}
                  className={`px-2.5 py-1 rounded-lg font-medium transition-all ${
                    selectedStatus === st
                      ? 'bg-emerald-500 text-white shadow-sm'
                      : 'text-ink-muted hover:text-white'
                  }`}
                >
                  {st}
                </button>
              ))}
            </div>

            {/* Search Input */}
            <div className="relative">
              <Search className="w-3.5 h-3.5 absolute left-3 top-1/2 -translate-y-1/2 text-ink-muted" />
              <input
                type="text"
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                placeholder="Search txn, order, customer..."
                className="pl-8 pr-3 py-1.5 rounded-xl bg-surface border border-surface-border text-xs text-white focus:outline-none focus:border-emerald-500/50 w-52"
              />
            </div>
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-surface/80 border-b border-surface-border text-ink-faint uppercase text-[10px] font-semibold">
              <tr>
                <th className="py-3 px-4">Transaction & Invoice</th>
                <th className="py-3 px-4">Order & Customer</th>
                <th className="py-3 px-4">Amount</th>
                <th className="py-3 px-4">Method</th>
                <th className="py-3 px-4">Status</th>
                <th className="py-3 px-4">Date</th>
                <th className="py-3 px-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-surface-border/50">
              {filteredPayments.map(p => (
                <tr key={p.id} className="hover:bg-surface/40 transition-colors">
                  <td className="py-3 px-4">
                    <div className="font-mono text-brand-400 font-semibold">{p.reference}</div>
                    <div className="text-[10px] font-mono text-ink-faint">{p.invoiceNumber}</div>
                  </td>
                  <td className="py-3 px-4">
                    <div className="font-medium text-white">{p.customerName}</div>
                    <div className="text-[10px] font-mono text-ink-muted">Order #{p.orderId}</div>
                  </td>
                  <td className="py-3 px-4 font-bold text-white font-mono">
                    {p.currency} {p.amount.toLocaleString(undefined, { minimumFractionDigits: 2 })}
                  </td>
                  <td className="py-3 px-4">
                    <span className="px-2 py-0.5 rounded-full bg-surface border border-surface-border text-[10px] font-mono text-ink-muted">
                      {p.method}
                    </span>
                  </td>
                  <td className="py-3 px-4">
                    <span className={`px-2.5 py-0.5 rounded-full text-[10px] font-mono border ${
                      p.status === 'PAID'
                        ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20'
                        : p.status === 'PENDING'
                        ? 'bg-amber-500/10 text-amber-400 border-amber-500/20'
                        : p.status === 'REFUNDED'
                        ? 'bg-sky-500/10 text-sky-400 border-sky-500/20'
                        : 'bg-rose-500/10 text-rose-400 border-rose-500/20'
                    }`}>
                      {p.status}
                    </span>
                  </td>
                  <td className="py-3 px-4 font-mono text-ink-faint">
                    {p.createdAt}
                  </td>
                  <td className="py-3 px-4 text-right">
                    <div className="flex items-center justify-end gap-1.5">
                      {p.status === 'PENDING' && (
                        <button
                          onClick={() => handleUpdateStatus(p.id, 'PAID')}
                          className="px-2 py-1 rounded-lg bg-emerald-500/10 text-emerald-400 hover:bg-emerald-500/20 border border-emerald-500/20 text-[10px] font-medium transition-all inline-flex items-center gap-1"
                          title="Verify and Mark as Paid"
                        >
                          <CheckCircle2 className="w-3 h-3" /> Verify Paid
                        </button>
                      )}

                      {p.status === 'PAID' && (
                        <button
                          onClick={() => handleUpdateStatus(p.id, 'REFUNDED')}
                          className="px-2 py-1 rounded-lg bg-rose-500/10 text-rose-400 hover:bg-rose-500/20 border border-rose-500/20 text-[10px] font-medium transition-all inline-flex items-center gap-1"
                          title="Process Refund"
                        >
                          <RotateCcw className="w-3 h-3" /> Refund
                        </button>
                      )}

                      <button
                        onClick={() => handleDownloadInvoice(p)}
                        className="px-2 py-1 rounded-lg bg-surface border border-surface-border text-ink-muted hover:text-white text-[10px] font-medium transition-all inline-flex items-center gap-1"
                        title="Download Invoice"
                      >
                        <Download className="w-3 h-3" /> Slip
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
